name: dev_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: 2.0.17
  provider: ^6.0.5
  readmore: ^3.0.0
  shared_preferences: ^2.5.2
  geolocator: ^13.0.2
  permission_handler: ^11.4.0
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/coffee_app/icons/
    - assets/coffee_app/images/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/coffee_app/fonts/Sora-ExtraBold.ttf
          weight: 800
        - asset: assets/coffee_app/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/coffee_app/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/coffee_app/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/coffee_app/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/coffee_app/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/coffee_app/fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/coffee_app/fonts/Sora-Thin.ttf
          weight: 100

flutter_gen:
  output: lib/src/assets/
  integrations:
    flutter_svg: true