name: dev_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: 2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/coffee_shop/icons/
    - assets/coffee_shop/images/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/coffee_shop/fonts/Sora-ExtraBold.ttf
          weight: 800
        - asset: assets/coffee_shop/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/coffee_shop/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/coffee_shop/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/coffee_shop/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/coffee_shop/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/coffee_shop/fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/coffee_shop/fonts/Sora-Thin.ttf
          weight: 100

flutter_gen:
  output: lib/src/generated/
  integrations:
    flutter_svg: true